version: "3"
services:
  api:
    image: tomcat:7-jdk8-openjdk
    build: ./api
    volumes:
      - /root/services/git/gow-api/build:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    tty: true
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /root/services/volumes/backups:/opt/backups
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    image: nginx
    volumes:
      # - ./templates:/etc/nginx/templates
      - web_build:/usr/share/nginx/html
    ports:
      - 80:80
    environment:
      - NGINX_HOST=gow.com
      - NGINX_PORT=80

    
volumes:
  pgdata:
  node_modules:
  web_build: