version: "3"
services:
  api:
    image: proactivehk/grails:3.3.2
    build: ./api
    volumes:
      - /root/services/git/gow-api:/app
    ports:
      - 8080:8080
    tty: true
  gowdb:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    image: nginx
    volumes:
      # - ./templates:/etc/nginx/templates
      - web_build:/usr/share/nginx/html
    ports:
      - 80:80
    environment:
      - NGINX_HOST=gow.com
      - NGINX_PORT=80
  ember:
    image: node:12
    build: ./ember
    volumes:
      - /root/services/git/gow-web:/app
      - web_build:/app/dist
    tmpfs:
      - /app/tmp
    ports:
      - 4200:4200
      - 7020:7020
      - 7357:7357

    
volumes:
  pgdata:
  node_modules:
  web_build: